<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210530064437 extends AbstractMigration
{
    
    public function getDescription(): string
    {
        return 'Data migration for the tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("INSERT INTO ram (id, name, memory) values (1, '16GBDDR3', 16);");  
        $this->addSql("INSERT INTO ram (id, name, memory) values (2, '32GBDDR3', 32);");  
        $this->addSql("INSERT INTO ram (id, name, memory) values (3, '128GBDDR4', 128);");   
        $this->addSql("INSERT INTO ram (id, name, memory) values (4, '64GBDDR4', 64);");  
        $this->addSql("INSERT INTO ram (id, name, memory) values (5, '64GBDDR3', 64);");  
        $this->addSql("INSERT INTO ram (id, name, memory) values (6, '4GBDDR3', 4);");  
        $this->addSql("INSERT INTO ram (id, name, memory) values (7, '16GBDDR4', 16);");  
        $this->addSql("INSERT INTO ram (id, name, memory) values (8, '32GBDDR4', 32);");  
        $this->addSql("INSERT INTO ram (id, name, memory) values (9, '96GBDDR3', 96);");  
        $this->addSql("INSERT INTO ram (id, name, memory) values (10, '8GBDDR3', 8);");  
        $this->addSql("INSERT INTO ram (id, name, memory) values (11, '128GBDDR3', 128);");  

        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 1, '2x2TBSATA2', 2000, 'SATA');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 2, '8x2TBSATA2', 2000, 'SATA');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 3, '4x480GBSSD', 480, 'SSD');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 4, '4x2TBSATA2', 2000, 'SATA');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 5, '4x1TBSATA2', 1000, 'SATA');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 6, '2x120GBSSD',  120, 'SSD');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 7, '2x500GBSATA2', 500, 'SATA');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 8, '2x1TBSATA2',  1000, 'SATA');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 9, '24x1TBSATA2', 1000, 'SATA');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 10, '8x120GBSSD', 120, 'SSD');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 11, '4x500GBSATA2', 500,  'SATA');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 12, '8x300GBSAS', 300, 'SAS');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 13, '8x3TBSATA2', 3000, 'SATA');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 14, '1x120GBSSD', 120, 'SSD');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 15, '6x1TBSATA2', 1000, 'SATA');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 16, '8x1TBSATA2', 1000, 'SATA');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 17, '4x960GBSSD', 960, 'SSD');");
        $this->addSql("INSERT INTO hard_disk_drive (id, name, storage, type) values ( 18, '2x240GBSSD', 240, 'SSD');");

        $this->addSql("INSERT INTO location (id, name) values ( 1, 'AmsterdamAMS-01');");
        $this->addSql("INSERT INTO location (id, name) values ( 2, 'Washington D.C.WDC-01');");
        $this->addSql("INSERT INTO location (id, name) values ( 3, 'San FranciscoSFO-12');");
        $this->addSql("INSERT INTO location (id, name) values ( 4, 'SingaporeSIN-11');");
        $this->addSql("INSERT INTO location (id, name) values ( 5, 'DallasDAL-10');");
        $this->addSql("INSERT INTO location (id, name) values ( 6, 'FrankfurtFRA-10');");
        $this->addSql("INSERT INTO location (id, name) values ( 7, 'Hong KongHKG-10');");

        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210Intel Xeon X3440' ,1, 1, 1, 49.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620' ,2, 2, 1, 119.00,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,2, 2, 1, 131.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('RH2288v32x Intel Xeon E5-2650V4' ,3, 3, 1, 227.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('RH2288v32x Intel Xeon E5-2620v4' ,4, 4, 1, 161.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1230v2' ,1, 1, 1, 72.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,5, 2, 1, 179.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X36302x Intel Xeon E5620' ,2, 2, 1, 106.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel G850' ,6, 5, 1, 39.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2667v4' ,3, 6, 1, 364.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3' ,3, 6, 1, 364.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3' ,3, 3, 1, 279.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v4' ,3, 3, 1, 286.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4' ,3, 3, 1, 239.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3' ,4, 6, 1, 199.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel G530' ,6, 7, 1, 35.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1220' ,1, 8, 1, 59.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3' ,4, 6, 1, 1044.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3' ,4, 6, 1, 756.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3' ,4, 6, 1, 874.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2' ,1, 8, 1, 89.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620' ,2, 9, 1, 199.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G91x Intel E5-1650v3' ,4, 4, 1, 154.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230' ,1, 5, 1, 84.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('DL20G9Intel Xeon E3-1270v5' ,7, 8, 1, 112.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G91x Intel E5-1620v3' ,8, 4, 1, 119.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620' ,5, 2, 1, 154.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,2, 2, 1, 142.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3' ,4, 4, 1, 209.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('RH2288v32x Intel Xeon E5-2650V4' ,3, 3, 1, 227.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('RH2288v32x Intel Xeon E5-2620v4' ,4, 4, 1, 161.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v4' ,4, 4, 1, 204.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1230v2' ,1, 1, 1, 72.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R7202x Intel Xeon E5-2643' ,2, 6, 1, 221.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5645' ,2, 2, 1, 129.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R6202x Intel Xeon E5-2650' ,9, 10, 1, 191.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230' ,1, 5, 1, 195.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620' ,5, 2, 1, 295.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,5, 2, 1, 355.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel G850' ,6, 5, 1, 163.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1230v2' ,1, 7, 1, 119.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,5, 2, 1, 272.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3' ,3, 3, 1, 367.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620' ,5, 2, 1, 212.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3' ,4, 4, 1, 277.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3' ,3, 6, 1, 389.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5645' ,2, 2, 1, 180.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R7202x Intel Xeon E5-2643' ,2, 6, 1, 246.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4' ,3, 3, 1, 341.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620' ,2, 2, 1, 166.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,5, 2, 1, 304.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3' ,4, 6, 1, 279.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel G530' ,6, 7, 1, 60.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1220' ,1, 8, 1, 110.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210Intel Xeon X3440' ,1, 1, 1, 83.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3' ,4, 6, 1, 1069.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3' ,4, 6, 1, 781.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3' ,4, 6, 1, 899.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel G850' ,6, 5, 1, 80.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620' ,2, 9, 1, 224.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G91x Intel E5-1620v3' ,8, 4, 1, 143.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,5, 2, 1, 252.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3' ,3, 3, 1, 347.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620' ,2, 2, 1, 146.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3' ,4, 4, 1, 257.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620' ,5, 2, 1, 192.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3' ,3, 6, 1, 369.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R7202x Intel Xeon E5-2643' ,2, 6, 1, 226.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4' ,3, 3, 1, 321.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3' ,4, 6, 1, 259.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3' ,4, 6, 1, 879.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3' ,4, 6, 1, 1049.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3' ,4, 6, 1, 761.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel G530' ,6, 7, 1, 40.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210Intel Xeon X3440' ,1, 1, 1, 63.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1220' ,1, 8, 1, 90.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel G850' ,6, 5, 1, 60.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620' ,2, 9, 1, 355.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,5, 2, 1, 190.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5645' ,2, 2, 1, 160.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210Intel Xeon X3440' ,1, 1, 1, 197.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,5, 2, 1, 386.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3' ,3, 3, 1, 481.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620' ,2, 2, 1, 280.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3' ,4, 4, 1, 391.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620' ,5, 2, 1, 326.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3' ,3, 6, 1, 503.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R7202x Intel Xeon E5-2643' ,2, 6, 1, 360.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4' ,3, 3, 1, 455.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3' ,4, 6, 1, 393.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3' ,4, 6, 1, 1013.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3' ,4, 6, 1, 1183.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3' ,4, 6, 1, 895.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel G530' ,6, 7, 1, 174.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1220' ,1, 8, 1, 224.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel G850' ,6, 5, 1, 194.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620' ,2, 9, 1, 489.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,5, 2, 1, 304.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5645' ,2, 2, 1, 294.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620' ,10, 5, 1, 1907.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2650' ,10, 5, 1, 1973.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620' ,10, 5, 1, 1907.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,10, 5, 1, 1967.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel G850' ,6, 11, 1, 1775.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230' ,10, 11, 1, 1807.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1240', 1, 5, 2, 105.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210Intel Xeon X3430', 10, 7, 2, 55.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2', 1, 8, 3, 121.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650V4', 3, 3, 4, 565.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v4', 3, 3, 2, 431.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4', 3, 3, 2, 380.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v3', 3, 6, 2, 360.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2650v3', 3, 6, 2, 413.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3', 4, 6, 3, 305.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3', 4, 6, 3, 303.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2630v3', 3, 6, 3, 362.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v3', 3, 6, 3, 360.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4', 3, 3, 3, 380.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2650v3', 3, 6, 3, 413.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3', 3, 6, 3, 411.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v4', 3, 3, 3, 431.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v4', 4, 6, 3, 319.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v4', 4, 6, 2, 319.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 1, 5, 170.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R5102x Intel Xeon E5620', 10, 8, 5, 165.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 5, 2, 5, 199.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 1, 1, 5, 206.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620', 2, 8, 5, 220.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620', 2, 8, 5, 225.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 1, 5, 297.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 1, 2, 170.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 2, 8, 2, 199.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620', 2, 8, 2, 220.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 8, 4, 228.00, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620', 2, 9, 5, 421.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('DL20G9Intel Xeon E3-1270v5', 7, 8, 3, 135.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Huawei RH1288v22x Intel Xeon E5-2650', 10, 8, 4, 269.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620V4', 4, 4, 4, 421.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Huawei RH2288V22x Intel Xeon E5-2620', 2, 8, 4, 239.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v4', 3, 3, 6, 395.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3', 4, 6, 6, 252.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3', 3, 6, 6, 342.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3', 3, 6, 6, 364.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3', 3, 6, 2, 437.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3', 4, 6, 5, 303.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3', 3, 6, 5, 411.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620' ,2, 2, 6, 99.00,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X36302x Intel Xeon E5620' ,2, 2, 6, 99.00,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620' ,2, 15, 6, 124.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620', 2, 8, 5, 225.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620' ,2, 2, 6, 187.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,2, 12, 6, 176.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 10, 5, 2, 183.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 8, 7, 228.00, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 10, 5, 2, 175.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2640v2' ,5, 16, 6, 249.00,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4' ,3, 3, 6, 316.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4' ,3, 3, 5, 380.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4' ,3, 17, 6, 362.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v4' ,3, 17, 6, 471.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5645', 10, 5, 2, 187.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620', 2, 8, 2, 225.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650V3', 3, 6, 4, 545.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3', 4, 6, 2, 303.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3', 3, 6, 2, 411.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3', 4, 6, 6, 254.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3', 4, 6, 2, 305.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3', 4, 6, 5, 305.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL160 G92x Intel Xeon E5-2630v3', 3, 6, 5, 382.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3', 3, 6, 5, 437.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2630v3', 3, 6, 2, 362.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2630v3', 3, 6, 6, 318.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R6302x Intel Xeon E5-2650v3', 3, 6, 4, 555.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 1, 7, 3, 105.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 1, 7, 2, 105.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270', 1, 7, 5, 110.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 1, 7, 5, 105.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2', 1, 8, 5, 121.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G6Intel G6950', 6, 1, 2, 49.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270', 1, 8, 2, 110.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G91x Intel E5-1650v3', 4, 6, 3, 263.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G91x Intel E5-1650v3', 4, 6, 5, 263.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G9Intel Xeon E5-1650v3', 4, 6, 7, 368.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G9Intel Xeon E5-1650v3', 4, 6, 4, 368.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3', 4, 6, 4, 1328.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3', 4, 6, 4, 1516.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3' ,4, 6, 6, 1044.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3', 4, 6, 4, 1787.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3' ,4, 6, 6, 756.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3' ,4, 6, 6, 874.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('DL20G9Intel Xeon E3-1270v5', 7, 8, 2, 135.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G91x Intel E5-1620v3', 7, 5, 2, 176.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v4' ,4, 4, 6, 204.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G6Intel G6950', 6, 1, 2, 43.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL20 G9Intel Xeon E3-1270v5', 7, 8, 4, 208.00, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL20 G9Intel Xeon E3-1270v5', 7, 8, 7, 208.00, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1230v2', 1, 7, 2, 139.00, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620', 2, 9, 2, 421.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620' ,2, 9, 6, 350.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270' ,1, 5, 6, 87.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 1, 5, 2, 103.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC8131x Intel E5-1650v2', 5, 6, 2, 233.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G91x Intel E5-1650v3' ,4, 4, 6, 219.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G91x Intel E5-1650v3' ,4, 4, 2, 275.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('DL20G9Intel Xeon E3-1270v5' ,7, 8, 2, 135.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1240', 1, 5, 2, 105.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G91x Intel E5-1650v3', 8, 5, 3, 239.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G6Intel Xeon X3440' ,10, 8, 2, 69.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('DL20G9Intel Xeon E3-1270v5' ,7, 8, 3, 135.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3', 3, 6, 3, 437.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G6Intel Xeon X3440', 10, 1, 2, 69.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 3, 2, 399.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,2, 2, 6, 142.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R7202x Intel Xeon E5-2643' ,2, 6, 6, 221.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620' ,2, 8, 6, 187.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,5, 2, 6, 165.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,1, 13, 6, 165.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,11, 14, 6, 247.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620', 2, 8, 2, 225.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620', 2, 8, 3, 225.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 1, 2, 297.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 1, 3, 297.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 5, 2, 3, 200.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 1, 1, 3, 200.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620', 2, 8, 3, 220.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R5102x Intel Xeon E5504' , 6, 5, 2, 104.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R5102x Intel Xeon E5620', 10, 8, 2, 165.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel G850', 6, 5, 4, 119.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R6302x Intel Xeon E5-2630v4', 4, 1, 4, 489.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R6302x Intel Xeon E5-2630v4', 4, 1, 7, 489.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620V4', 4, 4, 7, 421.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('RH2288v32x Intel Xeon E5-2620V4', 4, 4, 4, 319.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('RH2288v32x Intel Xeon E5-2650V4', 3, 3, 4, 429.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2', 10, 8, 4, 199.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel G850' ,1, 5, 6, 49.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R6202x Intel Xeon E5-2620v2', 10, 8, 4, 319.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2', 10, 8, 7, 199.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1230v2' ,1, 7, 6, 74.00,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL20G9Intel Xeon E3-1270v5' ,7, 8, 6, 112.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230' ,1, 5, 6, 75.00,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,5, 2, 6, 142.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 1, 7, 2, 235.59, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620', 2, 8, 2, 350.59, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620', 2, 8, 2, 355.59, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 1, 2, 427.59, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620' ,2, 8, 6, 295.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,11, 14, 6, 355.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2' ,1, 8, 6, 103.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2' ,1, 8, 3, 151.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 1, 7, 3, 135.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230' ,1, 7, 6, 94.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4', 3, 3, 2, 410.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel G850', 6, 5, 2, 97.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 5, 2, 5, 206.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620', 2, 9, 5, 451.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 8, 7, 719.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v4', 4, 6, 2, 349.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v4', 3, 3, 2, 461.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('DL20G9Intel Xeon E3-1270v5', 7, 8, 2, 169.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 1, 3, 327.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3' ,4, 6, 6, 277.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3' ,3, 6, 6, 367.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3' ,3, 6, 6, 389.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3' ,4, 6, 5, 333.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3', 3, 6, 5, 441.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3', 3, 6, 2, 467.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 1, 5, 200.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R5102x Intel Xeon E5620', 10, 8, 5, 195.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5645',2, 2, 5, 217.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 1, 1, 5, 367.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620', 2, 8, 5, 250.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620', 2, 8, 5, 255.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 1, 5, 327.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 1, 2, 200.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R5102x Intel Xeon E5620', 10, 8, 2, 195.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4' ,3, 3, 6, 341.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4', 3, 3, 5, 410.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620', 2, 8, 5, 255.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 1, 3, 327.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620', 2, 8, 3, 255.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 1, 2, 327.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620', 2, 8, 2, 255.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X36302x Intel Xeon E5620', 1, 8, 2, 202.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620', 2, 8, 2, 250.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620',2, 8, 2, 255.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 1, 1, 2, 367.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 1, 1, 3, 200.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620', 2, 8, 3, 250.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3', 4, 6, 2, 333.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3', 3, 6, 2, 441.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3', 4, 6, 6, 279.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3', 4, 6, 2, 335.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3', 4, 6, 5, 335.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL160 G92x Intel Xeon E5-2630v3', 3, 6, 5, 412.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3', 3, 6, 5, 467.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2630v3', 3, 6, 6, 343.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2630v3', 3, 6, 2, 412.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270' ,1, 8, 6, 99.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G6Intel G6950' ,6, 1, 2, 79.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 1, 7, 5, 135.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270', 1, 7, 5, 140.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC813MTQIntel Xeon E5-1650v2', 5, 6, 3, 233.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC813MTQIntel Xeon E5-1650v2', 5, 6, 2, 233.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G6Intel Xeon X3440', 10, 8, 2, 99.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2', 1, 8, 5, 151.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC813MTQIntel Xeon E5-1650v2', 5, 6, 5, 233.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270', 1, 8, 2, 140.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 1, 7, 2, 135.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3', 4, 6, 4, 1953.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3', 4, 6, 4, 2141.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3' ,4, 6, 6, 1069.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3', 4, 6, 4, 2412.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3' ,4, 6, 6, 781.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3' ,4, 6, 6, 899.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620', 2, 9, 2, 451.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620' ,2, 9, 6, 375.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1230v2' ,1, 7, 6, 96.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,11, 14, 6, 272.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620' ,2, 12, 6, 166.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,1, 13, 6, 190.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620' ,2, 8, 6, 212.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R7202x Intel Xeon E5-2643' ,2, 6, 6, 246.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,5, 2, 6, 190.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,5, 2, 2, 230.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 8, 4, 719.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 10, 5, 2, 143.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 1, 7, 3, 111.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210Intel Xeon X3430' ,10, 7, 2, 61.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2' ,1, 8, 3, 127.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 1, 7, 2, 111.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270', 1, 8, 2, 116.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4', 3, 3, 2, 386.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 1, 5, 176.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R5102x Intel Xeon E5620', 10, 8, 5, 171.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5645', 2, 2, 5, 193.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 5, 2, 5, 230.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 1, 1, 5, 230.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620', 2, 8, 5, 226.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620', 2, 8, 5, 231.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 1, 5, 303.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620', 2, 9, 5, 427.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 8, 7, 569.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620' ,2, 2, 6, 146.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v4' ,4, 6, 2, 464.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v4' ,3, 3, 2, 576.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('DL20G9Intel Xeon E3-1270v5' ,7, 8, 2, 280.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3' ,4, 6, 6, 257.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3' ,3, 6, 6, 347.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3', 4, 6, 5, 309.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3', 3, 6, 5, 417.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3', 3, 6, 2, 443.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3' ,3, 6, 6, 369.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620' ,2, 8, 5, 231.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2640v2' ,5, 16, 6, 279.00,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4' ,3, 3, 6, 321.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4', 3, 3, 5, 386.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620', 2, 8, 2, 231.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620' ,2, 8, 4, 569.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3', 4, 6, 2, 309.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3', 3, 6, 2, 417.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL160 G92x Intel Xeon E5-2630v3', 3, 6, 6, 323.99, 'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3', 4, 6, 6, 259.99, 'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3', 4, 6, 2, 311.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL160 G92x Intel Xeon E5-2630v3', 3, 6, 2, 388.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3', 4, 6, 5, 311.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL160 G92x Intel Xeon E5-2630v3', 3, 6, 5, 388.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3', 3, 6, 5, 443.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270' ,1, 8, 6, 96.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230' ,1, 7, 5, 111.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270' ,1, 7, 5, 116.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC813MTQIntel Xeon E5-1650v2' ,5, 6, 2, 209.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G6Intel Xeon X3440' ,10, 8, 2, 75.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2', 1, 8, 5, 127.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC813MTQIntel Xeon E5-1650v2', 5, 6, 5, 209.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230' ,1, 7, 6, 92.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G6Intel G6950' ,6, 1, 2, 55.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC813MTQIntel Xeon E5-1650v2', 5, 6, 3, 209.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3', 4, 6, 4, 1553.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3', 4, 6, 4, 1741.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3' ,4, 6, 6, 1049.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3', 4, 6, 4, 2012.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3' ,4, 6, 6, 761.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3' ,4, 6, 6, 879.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620' ,2, 9, 2, 427.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620' ,2, 9, 6, 355.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R7202x Intel Xeon E5-2643' ,2, 6, 6, 226.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620' ,2, 8, 6, 192.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,11, 14, 6, 252.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,1, 13, 6, 170.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,5, 2, 6, 170.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,5, 2, 3, 200.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,1, 1, 3, 200.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620' ,2, 8, 3, 226.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R5102x Intel Xeon E5504' ,6, 5, 2, 110.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 1, 2, 176.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5645' ,2, 2, 2, 193.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 5, 2, 2, 200.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,1, 1, 2, 230.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620' ,2, 8, 2, 231.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620' ,2, 8, 3, 231.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,11, 1, 2, 303.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,11, 1, 3, 303.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620' ,2, 8, 2, 226.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R5102x Intel Xeon E5620' ,10, 8, 2, 171.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G6Intel Xeon X3440' ,6, 7, 2, 236.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230' ,1, 7, 2, 272.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270' ,1, 8, 2, 277.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2', 1, 8, 3, 288.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210Intel Xeon X3440', 1, 1, 2, 237.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230' ,1, 7, 3, 272.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210Intel Xeon X3430' ,10, 7, 2, 222.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230' ,1, 7, 6, 226.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270' ,1, 8, 6, 230.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4', 3, 3, 2, 547.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R5102x Intel Xeon E5620' ,10, 8, 5, 332.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 1, 5, 337.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5645' ,2, 2, 5, 354.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 5, 2, 5, 367.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 1, 1, 5, 367.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620', 2, 8, 5, 387.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620', 2, 8, 5, 392.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 1, 5, 464.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620', 2, 9, 5, 588.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v4', 4, 6, 2, 994.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v4', 3, 3, 2, 1106.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('DL20G9Intel Xeon E3-1270v5' ,7, 8, 2, 810.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4' ,3, 3, 2, 1055.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3' ,4, 6, 6, 391.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3' ,3, 6, 6, 481.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3' ,3, 6, 5, 578.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3' ,4, 6, 5, 470.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3' ,3, 6, 6, 503.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3' ,3, 6, 2, 604.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620' ,2, 8, 5, 392.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4' ,3, 3, 6, 455.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2630v4', 3, 3, 5, 547.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X36302x Intel Xeon E5620', 1, 8, 2, 339.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620', 2, 8, 3, 392.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650', 11, 1, 3, 464.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620' ,2, 8, 2, 392.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2620v3', 4, 6, 2, 470.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2650v3', 3, 6, 2, 578.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL160 G92x Intel Xeon E5-2630v3' ,3, 6, 6, 457.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3' ,4, 6, 6, 393.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3' ,4, 6, 2, 472.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2620v3' ,4, 6, 5, 472.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL160 G92x Intel Xeon E5-2630v3', 3, 6, 5, 549.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R730XD2x Intel Xeon E5-2670v3' ,3, 6, 5, 604.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180 G92x Intel Xeon E5-2630v3' ,3, 6, 2, 549.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC813MTQIntel Xeon E5-1650v2', 5, 6, 2, 370.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC813MTQIntel Xeon E5-1650v2', 5, 6, 3, 370.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230' ,1, 7, 5, 272.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1270' ,1, 8, 5, 277.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R210-IIIntel Xeon E3-1270v2', 1, 8, 5, 288.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC813MTQIntel Xeon E5-1650v2' ,5, 6, 5, 370.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G6Intel G6950', 6, 1, 2, 216.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3', 4, 6, 4, 4203.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3', 4, 6, 4, 4391.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3' ,4, 6, 6, 1183.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4850v3' ,4, 6, 4, 4662.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4820v3' ,4, 6, 6, 895.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R9304x Intel Xeon E7-4830v3' ,4, 6, 6, 1013.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620' ,2, 9, 2, 588.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Supermicro SC846Intel Xeon E5620' ,2, 9, 6, 489.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R7202x Intel Xeon E5-2643' ,2, 6, 6, 360.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R720XD2x Intel Xeon E5-2620' ,2, 8, 6, 326.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620' ,2, 12, 6, 280.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420' ,1, 13, 6, 304.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,11, 14, 6, 386.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 1, 1, 3, 367.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620' ,2, 8, 3, 387.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R5102x Intel Xeon E5504', 6, 5, 2, 271.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('Dell R5102x Intel Xeon E5620', 10, 8, 2, 332.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5620', 2, 1, 2, 337.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL180G62x Intel Xeon E5645' ,2, 2, 2, 354.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380eG82x Intel Xeon E5-2420', 1, 1, 2, 367.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620' ,2, 8, 2, 392.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,11, 1, 2, 464.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('IBM X3650M42x Intel Xeon E5-2620' ,2, 8, 2, 387.79, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 10, 1, 2, 2169.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620', 10, 5, 5, 2289.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,10, 5, 5, 2361.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL120G7Intel Xeon E3-1230', 10, 1, 5, 2169.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,10, 5, 6, 1967.99,'EUR');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2620', 10, 5, 2, 2289.99, 'USD');");
        $this->addSql("INSERT INTO servers (name, ram_id, hard_disk_drive_id, location_id, price, currency) VALUES ('HP DL380pG82x Intel Xeon E5-2650' ,10, 5, 2, 2361.99, 'USD');");
    }

    public function down(Schema $schema): void
    {
        $this->addSql("TRUNCATE TABLE ram;");
        $this->addSql("TRUNCATE TABLE hard_disk_drive;");
        $this->addSql("TRUNCATE TABLE location;");
        $this->addSql("TRUNCATE TABLE servers;");
    }
}
